version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=LoginOauth2Demo_Identity
      - LoginOauth2Demo_DB=LoginOauth2Demo_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
